//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materia
    {
        public string Id { get; set; }
        public string Nombre { get; set; }
        public string Creditos { get; set; }
        public string Calificacion { get; set; }
        public string Evaluacion { get; set; }
    }
}
